name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  proof:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./
          # TODO: remove once kai-course-notes.kaichen.dev is live on Vercel
          url_ignore_re: ^https://kai-course-notes\.kaichen\.dev
